# Generated by Django 5.0.4 on 2024-05-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
    ]
