# Generated by Django 5.0.4 on 2024-05-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('type', models.CharField(choices=[('factory', 'завод'), ('retail network', 'розничная сеть'), ('individual entrepreneur', 'ИП')], max_length=50, verbose_name='тип')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('country', models.CharField(verbose_name='страна')),
                ('city', models.CharField(verbose_name='город')),
                ('street', models.CharField(verbose_name='улица')),
                ('house', models.CharField(verbose_name='номер дома')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='задолженность')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='время и дата создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.networkitem', verbose_name='поставщик')),
                ('products', models.ManyToManyField(to='traders.product', verbose_name='продукты')),
            ],
        ),
        migrations.CreateModel(
            name='SalesNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='traders.networkitem', verbose_name='потребитель')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='traders.networkitem', verbose_name='распространитель')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='traders.networkitem', verbose_name='производитель')),
            ],
        ),
    ]
