# Generated by Django 5.0.4 on 2024-05-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkitem',
            options={'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
        migrations.AlterModelOptions(
            name='salesnetwork',
            options={'verbose_name': 'Торговая сеть', 'verbose_name_plural': 'Торговые сети'},
        ),
    ]
