# Generated by Django 5.0.4 on 2024-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_alter_networkitem_options_alter_salesnetwork_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='задолженность'),
        ),
        migrations.AlterField(
            model_name='networkitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='traders.product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='networkitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traders.networkitem', verbose_name='поставщик'),
        ),
    ]
