# Generated by Django 5.0.4 on 2024-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_alter_networkitem_debt_alter_networkitem_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='задолженность '),
        ),
    ]
