# Generated by Django 5.0.4 on 2024-05-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_alter_networkitem_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='7A Pro', max_length=250, verbose_name='модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Philips', max_length=250, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default='2024-05-02', verbose_name='дата выхода продукта на рынок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='задолженность'),
        ),
    ]
